/* SQLCMD mode required */

:setvar Root "F:\DB\Project\BanckManagement\Scripts_FIXED_Coherent_Final\Scripts"

:r "$(Root)\TableCreation\TableCreation_FULL_FINAL_SAFE_REBUILD.sql"
:r "$(Root)\Functions\PasswordHash.sql"

:r "$(Root)\Rules\Schema_CustomerAccessAndBranchLedger.sql"
:r "$(Root)\Rules\Schema_AccountModuleSupport_SELF_SERVICE.sql"
:r "$(Root)\Rules\Schema_EmployeeModuleSupport.sql"
:r "$(Root)\Rules\EMPB_PreventDateOverlap.sql"
:r "$(Root)\Rules\ApplyAccessRules.sql"
:r "$(Root)\Rules\99_Function_UserHasEffectiveRole.sql"

:r "$(Root)\Triggers\TransactionTriggers\Trigger_Transactions_EnforceTypePattern_Update.sql"
:r "$(Root)\Triggers\AccountTriggers\Trigger_Account_PreventCloseWithPending.sql"
:r "$(Root)\Triggers\AccountTriggers\Trigger_Account_SyncBranchLedger.sql"
:r "$(Root)\Triggers\CustomerTriggers\Trigger_Customer_PreventDeactivateWithPending.sql"
:r "$(Root)\Triggers\LoanTriggers\Trigger_SyncInstallmentStatus.sql"

:r "$(Root)\StoredProcedures\CustomerProcedures\Procedure_Customer_Create.sql"
:r "$(Root)\StoredProcedures\CustomerProcedures\Procedure_Customer_Update.sql"
:r "$(Root)\StoredProcedures\CustomerProcedures\Procedure_Customer_Delete.sql"
:r "$(Root)\StoredProcedures\CustomerProcedures\Procedure_Customer_Search.sql"

:r "$(Root)\StoredProcedures\UserProcedures\Procedure_HighAdmin_CreateInitialUser.sql"
:r "$(Root)\StoredProcedures\UserProcedures\Procedure_User_SignUp_UPDATED.sql"
:r "$(Root)\StoredProcedures\UserProcedures\Procedure_User_Login.sql"
:r "$(Root)\StoredProcedures\UserProcedures\Procedure_User_Logout.sql"
:r "$(Root)\StoredProcedures\Session\Procedure_User_ValidateSession.sql"

:r "$(Root)\StoredProcedures\TransactionProcedures\Desposit_SP.sql"
:r "$(Root)\StoredProcedures\TransactionProcedures\Withdraw_SP.sql"
:r "$(Root)\StoredProcedures\TransactionProcedures\Transfer_SP.sql"
:r "$(Root)\StoredProcedures\TransactionProcedures\TransactionFinalizer.sql"
:r "$(Root)\StoredProcedures\TransactionProcedures\Procedure_ProcessPendingBatch.sql"
:r "$(Root)\StoredProcedures\TransactionProcedures\Procedure_ReverseTransaction.sql"

:r "$(Root)\StoredProcedures\AccountProcedures\Procedure_Account_Open.sql"
:r "$(Root)\StoredProcedures\AccountProcedures\Procedure_Account_GetInfo.sql"
:r "$(Root)\StoredProcedures\AccountProcedures\Procedure_Account_Search.sql"
:r "$(Root)\StoredProcedures\AccountProcedures\Procedure_Account_Close.sql"
:r "$(Root)\StoredProcedures\AccountProcedures\Procedure_Account_Freeze_Unfreeze.sql"
:r "$(Root)\StoredProcedures\AccountProcedures\Procedure_Account_ChangeType.sql"
:r "$(Root)\StoredProcedures\AccountProcedures\Procedure_Account_DormantSweep.sql"
:r "$(Root)\StoredProcedures\AccountProcedures\Procedure_Account_ApplyMonthlyInterest.sql"
:r "$(Root)\StoredProcedures\AccountProcedures\Procedure_AccountHistory.sql"

:r "$(Root)\StoredProcedures\LoanProcedures\Procedure_Loan_Create.sql"
:r "$(Root)\StoredProcedures\LoanProcedures\Procedure_Loan_GetStatus.sql"
:r "$(Root)\StoredProcedures\LoanProcedures\Procedure_Loan_PayInstallment.sql"
:r "$(Root)\StoredProcedures\LoanProcedures\Procedure_Loan_ProcessOverdueInstallments.sql"

:r "$(Root)\StoredProcedures\Employees\Procedure_Branch_GetInfo.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_EMPBranchHistory_Get.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_Employee_GetInfo.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_Employee_Search.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_Employee_Hire.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_Employee_CreateUserAccount.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_Employee_ChangeJobTitle.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_Employee_Fire.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_Employee_Suspend.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_EmployeeTransfer_RequestByEmployee.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_EmployeeTransfer_RequestByManager.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_EmployeeTransfer_ApproveCurrentManager.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_EmployeeTransfer_ApproveDestinationManager.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_HighAdmin_HireManager.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_HighAdmin_PromoteToManager.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_HighAdmin_DowngradeManager.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_HighAdmin_ReplaceBranchManager.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_HighAdmin_FireManager.sql"
:r "$(Root)\StoredProcedures\Employees\Procedure_HighAdmin_SuspendManager.sql"

-- Optional sample data:
-- :r "$(Root)\SampleData\SampleData.sql"