/* =========================================================
   Procedure_Account_ApplyMonthlyInterest.sql
   sp_Account_ApplyMonthlyInterest

   Higher-level protocol (same set-based pattern as
   sp_Transaction_ProcessPendingBatch / sp_Loan_ProcessOverdueInstallments)
   that credits interest to every eligible account in one pass,
   once a month.

   ASSUMPTION: AccountType.InterestRate is already a MONTHLY
   rate (the project only specifies "calculated monthly based on
   each account type's interest rate", with no annual-to-monthly
   conversion mentioned), so the amount credited is simply:

       InterestAmount = ROUND(Balance * InterestRate / 100, 2)

   Eligible accounts: AccountStatus = 'Active', Balance > 0, and
   AccountType.InterestRate > 0.

   Unlike a customer-initiated Deposit, this is a system-generated
   event with no fraud/throttling concern, so it is recorded as
   an ALREADY-'Completed' Transactions row (TransactionTypeID =
   'Interest') with no Pending hold -- it does not go through
   sp_Transaction_Deposit/sp_Transaction_Finalize. Account.Balance
   is updated directly in the same statement, and
   TR_Account_SyncBranchLedger (fired by that Account UPDATE)
   takes care of keeping Branch.Balance/BranchLedger in sync
   automatically -- this procedure does not need to know either
   of those objects exist.

   Intended caller: a SQL Server Agent job, run once a month (see
   AgentJob_ApplyMonthlyInterest.sql). Can also be run manually.

   Must run AFTER TableCreation.sql,
   Schema_CustomerAccessAndBranchLedger.sql (needs the 'Interest'
   TransactionType), and
   Trigger_Transactions_EnforceTypePattern_Update.sql.
   ========================================================= */

CREATE OR ALTER PROCEDURE dbo.sp_Account_ApplyMonthlyInterest
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    BEGIN TRY
        BEGIN TRANSACTION;

        DECLARE @InterestTypeID INT;
        SELECT @InterestTypeID = TransactionTypeID FROM dbo.TransactionType WHERE TypeName = 'Interest';

        IF @InterestTypeID IS NULL
        BEGIN
            RAISERROR('Interest transaction type is not configured.', 16, 1);
            ROLLBACK TRANSACTION;
            RETURN;
        END;

        ----------------------------------------------------
        -- Step 1: snapshot every eligible account and its
        -- computed interest amount.
        ----------------------------------------------------
        IF OBJECT_ID('tempdb..#InterestBatch') IS NOT NULL DROP TABLE #InterestBatch;

        SELECT
            a.AccountID,
            ROUND(a.Balance * at.InterestRate / 100.0, 2) AS InterestAmount
        INTO #InterestBatch
        FROM dbo.Account a
        INNER JOIN dbo.AccountType at ON a.AccountTypeID = at.AccountTypeID
        WHERE a.AccountStatus = 'Active'
          AND a.Balance > 0
          AND at.InterestRate > 0;

        DELETE FROM #InterestBatch WHERE InterestAmount <= 0;

        IF NOT EXISTS (SELECT 1 FROM #InterestBatch)
        BEGIN
            COMMIT TRANSACTION;

            SELECT
                CAST(NULL AS INT)           AS AccountID,
                CAST(NULL AS DECIMAL(18,2)) AS InterestAmount,
                CAST(NULL AS INT)           AS TransactionID
            WHERE 1 = 0;

            RETURN;
        END;

        ----------------------------------------------------
        -- Step 2: insert one already-Completed Transactions row
        -- per account, capturing the generated TransactionID.
        ----------------------------------------------------
        IF OBJECT_ID('tempdb..#InterestTx') IS NOT NULL DROP TABLE #InterestTx;
        CREATE TABLE #InterestTx (AccountID INT, TransactionID INT, InterestAmount DECIMAL(18,2));

        DECLARE @Now DATETIME = GETDATE();

        -- MERGE used purely to capture, per source row, the
        -- IDENTITY value generated by each corresponding insert
        -- (OUTPUT on a plain multi-row INSERT cannot be joined
        -- back to the source rows by anything other than insertion
        -- order, which is not guaranteed).
        MERGE INTO dbo.Transactions AS tgt
        USING #InterestBatch AS src
        ON 1 = 0  -- never match; this MERGE is insert-only
        WHEN NOT MATCHED THEN
            INSERT (TransactionTypeID, FromAccountID, ToAccountID, EmployeeID, Amount,
                    TransactionDate, TransactionStatus, ReadyToCompleteAt, CompletedAt, Description)
            VALUES (@InterestTypeID, NULL, src.AccountID, NULL, src.InterestAmount,
                    @Now, 'Completed', @Now, @Now, N'Monthly interest credit')
        OUTPUT src.AccountID, inserted.TransactionID, src.InterestAmount
        INTO #InterestTx (AccountID, TransactionID, InterestAmount);

        ----------------------------------------------------
        -- Step 3: apply the balance effect. This UPDATE is what
        -- fires TR_Account_SyncBranchLedger, which propagates
        -- the change into Branch.Balance / BranchLedger.
        ----------------------------------------------------
        UPDATE a
        SET a.Balance = a.Balance + it.InterestAmount
        FROM dbo.Account a
        INNER JOIN #InterestTx it ON a.AccountID = it.AccountID;

        ----------------------------------------------------
        -- Step 4: audit log, one row per account credited.
        ----------------------------------------------------
        INSERT INTO dbo.AuditLog (UserID, ActionType, TableName, RecordID, Details)
        SELECT
            NULL,
            'InterestApplied',
            'Account',
            it.AccountID,
            CONCAT('Monthly interest of ', it.InterestAmount, ' credited via TransactionID ', it.TransactionID)
        FROM #InterestTx it;

        COMMIT TRANSACTION;

        ----------------------------------------------------
        -- Step 5: report what happened.
        ----------------------------------------------------
        SELECT AccountID, InterestAmount, TransactionID
        FROM #InterestTx
        ORDER BY AccountID;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END;
GO
